### ISSUE TITLE
如何跟踪文档的更新

### ISSUE THREAD

**Issue by chenzefeng09** [apache/incubator-weex-site#291]
我很关心文档更新了哪些内容，但是现在没有一个地方能够集中的展示这些。希望有个What's new on Weex,就像flutter的官网那样
![image](https://user-images.githubusercontent.com/7556537/50509776-0f694080-0ac2-11e9-8a8b-eb1e91d12e43.png)

而不是总要关注git上合并了哪些pr

**Comment by YorkShen** [comment]
Weex do have an English version of [release note](https://weex.apache.org/release-note.html).

You may subscribe [weex mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list). All the information about release will be discussed through mailing list.

BTW, under the rule of Apache Software Foundation, the official language for project is English. So there is only English version of Release Note.
