### ISSUE TITLE
<richtext> Summary 

### ISSUE THREAD

**Issue by ligxe** [apache/incubator-weex-site#306]
http://weex.io/zh/docs/components/richtext.html#%E6%A0%B7%E5%BC%8F

a document problem
At <richtext> - Summary - Notes:
 '<a> on iOS will have a color:blue style, and children of <a> can not override this style. This only happens on iOS. '
Practice found on iOS set color style is  effective (test device: iphone7 ios10 ), then,  Is the document out of date or am I not fully testing it?

In addition, `<richtext>` - Example . The binding event is `itemclick` instead of `onitemclick`  in demo code.

**Comment by wqyfavor** [comment]
Yes, the document is right and I fixed the demo. http://dotwe.org/vue/f748b0cee3991522a66d4376b66a4f2a

By the way, as the demo shows, if <span style="font-size:42;color:#FF5400;">TAOBAO</span> is in a 'a', 'TAOBAO' is blue and not '#FF5400'.
