### ISSUE TITLE
这个js-service是用来做什么的

### ISSUE THREAD

**Issue by snailyuan** [apache/incubator-weex-site#309]
类似是一个可以提供用来做全局的实例吗，文档没太看懂是可以用来做什么用

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> What is this js-service used for?

JSService is the same as `vendor.js` in front-end engineer world, it is usually used to remove the file of  each page by provide a common js in global context.

On each page of the document, there is a button called **编辑此页** or **Edit this Page**. Feel free to give us a PR to improve the document,
