### ISSUE TITLE
【GCanvas】iOS SendVertexBufferToGPU Crash

### ISSUE THREAD

**Issue by c1394393468** [apache/incubator-weex-site#320]
在iOS 渲染成功后放置几分钟再这里崩溃

`
GCanvas2dContext.cpp
void GCanvasContext::SendVertexBufferToGPU(const GLenum geometry_type)
{
if (mVertexBufferIndex == 0)
{
return;
}

glDrawArrays(geometry_type, 0, mVertexBufferIndex);  // Crash Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)
mVertexBufferIndex = 0;
}
`
另外是渲染完成后 ，Log会一直打是否正常？

**Comment by YorkShen** [comment]
This is not the place to report bugs for weex or gcanvas, you should report bug in [other repo](https://github.com/weex-plugins/weex-plugin-gcanvas/issues)
