### ISSUE TITLE
jsbridge

### ISSUE THREAD

**Issue by bingwang12** [apache/incubator-weex-site#322]
https://weex.io/
还是希望能够讲解一下webview里面的页面如何调用原生的功能，譬如照相机

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Still hope to explain how the pages in webview call native functions, such as cameras.

You may take webview as a system's webview, if it support calling camera(I seriously doubt it), then it would do fine in webview of Weex.
