### ISSUE TITLE
建议slider添加方向控制和切换速率控制

### ISSUE THREAD

**Issue by newshow** [apache/incubator-weex-site#326]
http://weex.apache.org/zh/docs/components/slider.html#%E7%A4%BA%E4%BE%8B

**Comment by YorkShen** [comment]
This repo is not for feature request, if you want a feature to be discussed, send an email to [weex mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)
