### ISSUE TITLE
<textarea>多行属性是rows不是row

### ISSUE THREAD

**Issue by wslaimin** [apache/incubator-weex-site#332]
http://weex.incubator.apache.org/zh/docs/components/textarea.html#%E7%A4%BA%E4%BE%8B

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> <textarea> multi-line attribute is rows is not row

On each page of the document, there is a button called **编辑此页** or **Edit this Page**, just click it, and give us a PR.
