### ISSUE TITLE
搜索icon或图标或font，都找不到我要的自定义图标，还让不让人玩了？

### ISSUE THREAD

**Issue by aa0604** [apache/incubator-weex-site#337]
http://weex.apache.org/zh/guide/introduction.html#下一步

**Comment by erha19** [comment]
![image](https://user-images.githubusercontent.com/9823838/53615073-343f7880-3c17-11e9-9ded-290ec666ab84.png)

**Comment by erha19** [comment]
@aa0604 我们之前的搜索采用的是第三方algolia的搜索功能，目前官网更新后需要相应更新相应的数据库，这块正在邮件推进之中，下周会处理这个问题带来更好的搜索体验。

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question: Search for the icon or icon or font, I can't find the custom icon I want, and let it not be played.

The issue has been fixed, Thanks for your reply.
