### ISSUE TITLE
There is no write height required for the component <web>

### ISSUE THREAD

**Issue by zj1024** [apache/incubator-weex-site#345]
https://weex.apache.org/zh/docs/components/web.html#%E4%BA%8B%E4%BB%B6

<web> component how to set full screen ?
 I try to use .WXEnvironment.deviceHeight/ this.WXEnvironment.scale
but it has mistake about height

**Comment by YorkShen** [comment]
Thanks for your feedback.

If you are asking question about the behaviour, you should ask in https://github.com/apache/incubator-weex.

I will just close the PR, thanks
