### ISSUE TITLE
这里少了一个引号 weex.requireModule("event").showParams("hello Weex)

### ISSUE THREAD

**Issue by ShitanLi** [apache/incubator-weex-site#348]
https://weex.apache.org/zh/guide/extend/extend-ios.html#%E8%87%AA%E5%AE%9A%E4%B9%89-handler

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> There is one quote left here weex.requireModule("event").showParams("hello Weex)

Please give us a PR, thanks

**Comment by YorkShen** [comment]
Closed by #531
