### ISSUE TITLE
应该加一个蒙版mask

### ISSUE THREAD

**Issue by xiujianyao** [apache/incubator-weex-site#349]
https://weex.apache.org/zh/docs/modules/modal.html#prompt

**Comment by janpio** [comment]
Can you elaborate a bit please? I am not sure if you are asking something or suggesting a feature. Thanks.

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Should add a mask mask

I am not sure if you are asking for a new feature, if so, please talk it in the [mailing list]()https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list

**Comment by YorkShen** [comment]
As this issue is not updated for a while, I will just close it.

Feel free to reopen it if you have further questions.
