### ISSUE TITLE
为什么组件实例经常写不出来

### ISSUE THREAD

**Issue by iceading** [apache/incubator-weex-site#354]
https://weex.apache.org/zh/docs/modules/picker.html#picktime

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Why are component instances often not written?

What's the problem ? Could you please provide a [runnable demo](http://dotwe.org/vue) ?

**Comment by YorkShen** [comment]
As this issue is not updated for a while, I will just close it.

Feel free to reopen it if you have further questions.
