### ISSUE TITLE
the doc in zh-cn has error?

### ISSUE THREAD

**Issue by xiaoyang678** [apache/incubator-weex-site#368]
https://weex.apache.org/zh/guide/introduction.html#%E6%A6%82%E8%BF%B0

**Comment by xiaoyang678** [comment]
你可以浏览、修改、新建各种基于 Vuew.js 的单页面例子
Vuew.js?? may be vue.js?

**Comment by YorkShen** [comment]
This issue has been fixed. Thanks for your report.
