### ISSUE TITLE
关于插件市场

### ISSUE THREAD

**Issue by henancheng** [apache/incubator-weex-site#374]
支付也是一大块，建议支持淘宝，微信支付，提前做出插件。很重要。

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Payment is also a big chunk, it is recommended to support Taobao, WeChat payment, and make plug-ins in advance. Very important.

First of all, plugin is not a part of Apache Weex now.

BTW, according to [document](https://weex.apache.org/guide/contribute/how-to-contribute.html#ask-or-answer-questions), Github issue is only for bug report. If you have feature request, please subscribe the [mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#ask-or-answer-questions) and discuss in the mailing list.
