### ISSUE TITLE
大标题写错了，Instance

### ISSUE THREAD

**Issue by parkerzhu** [apache/incubator-weex-site#375]
https://weex.apache.org/zh/docs/api/android-apis.html#%E5%85%B6%E5%AE%83%E7%9A%84%E4%B8%80%E4%BA%9B%E6%8E%A5%E5%8F%A3%E4%BB%8B%E7%BB%8D

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: The headline is wrong, Instance

Please give us a PR, thanks.
