### ISSUE TITLE
 input上在input事件加上正则 不起作用

### ISSUE THREAD

**Issue by shicaifeng123** [apache/incubator-weex-site#377]
input输入框在家正则不起作用，在input事件中写正则是改变了，但  是input输入框内容  没有改变，就是控制非数字和 非字母类的输入的正则

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: The input input box does not work at home, and the tying in the input event is changed, but the input input box content is unchanged, that is, the regularity of controlling the input of non-numeric and non-letter types.

Please report the bug in [incubator-weex](https://github.com/apache/incubator-weex) repos as this repo is only for document, thanks.
