### ISSUE TITLE
GCanvas demo用不了找不到注册组件canvas

### ISSUE THREAD

**Issue by jianguo-sun** [apache/incubator-weex-site#378]
https://weex.apache.org/zh/community/weex-third-party-extensions.html

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: GCanvas demo can't find the registered component canvas

As its description, gcanvas is a third-party plugin, Apache Weex is not responsible for third-party plugin. So you should ask this question in GCanvas repo, not here.
