### ISSUE TITLE
怎么能监听video的缓冲事件呢

### ISSUE THREAD

**Issue by kellerjin** [apache/incubator-weex-site#379]
https://weex.apache.org/zh/docs/components/video.html#%E7%A4%BA%E4%BE%8B

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: How can I listen to the video buffer event?

Anything that doesn't list in the document is not supported, thanks.
