### ISSUE TITLE
scroller+refresh的bug，发现半年了，请尽快修复

### ISSUE THREAD

**Issue by wujianqiang6** [apache/incubator-weex-site#380]
https://weex.apache.org/zh/docs/components/refresh.html#%E7%A4%BA%E4%BE%8B

item是可点击组件，进入页面第一次滑动的时候，Android端会默认的进行一次下拉刷新
bug实例地址：http://dotwe.org/vue/707d344cf67f726c1312b5a161b702c7

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: item是可点击组件，进入页面第一次滑动的时候，Android端会默认的进行一次下拉刷新 bug实例地址：http://dotwe.org/vue/707d344cf67f726c1312b5a161b702c7

Please report the bug in [incubator-weex](https://github.com/apache/incubator-weex) repos as this repo is only for document, thanks.
