### ISSUE TITLE
web端modal的alert、confirm和prompt回退的bug

### ISSUE THREAD

**Issue by hunan-liy** [apache/incubator-weex-site#384]
web端modal的alert、confirm和prompt在显示的时候还可以进行回退操作，回退时modal弹出不会被关闭

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: The web-side modal alert, confirm, and prompt can also be rolled back when displayed, and the modal pop-up will not be closed when the rollback is performed.

Please report the bug in [incubator-weex](https://github.com/apache/incubator-weex) repos as this repo is only for document, thanks.
