### ISSUE TITLE
建议支持本地安装

### ISSUE THREAD

**Issue by wlh0101** [apache/incubator-weex-site#387]
https://weex.apache.org/zh/guide/develop/setup-develop-environment.html#%E5%BC%80%E5%8F%91

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Recommended to support local installation

According to [document](https://weex.apache.org/guide/contribute/how-to-contribute.html#ask-or-answer-questions), Github issue is only for bug report. If you have feature request, please subscribe the [mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#ask-or-answer-questions) and discuss in the mailing list.
