### ISSUE TITLE
weex使用navigator做页面跳转URL地址的id应该怎么获取？请做出相关示例

### ISSUE THREAD

**Issue by yinianjiqi** [apache/incubator-weex-site#393]

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Weex use navigator to do the page id URL address id how to get? Please make a relevant example.

First, I don't get your idea of **id**.

Anyway, this is not the problem of document.
