### ISSUE TITLE
[WXCoreBridge setDeviceSize:[UIScreen mainScreen].bounds.size];   这个类没有这个方法

### ISSUE THREAD

**Issue by liuxinghy1987** [apache/incubator-weex-site#394]
https://weex.apache.org/zh/guide/develop/integrate-to-iOS-app.html#_6-%E5%9C%A8-ipad-%E4%B8%AD%E4%BD%BF%E7%94%A8-weex

**Comment by YorkShen** [comment]
This is implemented in release 0.28.
