### ISSUE TITLE
Weex Playground 调试过程中经常性崩溃，并且无法开启js调试

### ISSUE THREAD

**Issue by wangyunlong0418** [apache/incubator-weex-site#398]
https://weex.apache.org/zh/guide/debug/debug.html#%E5%BC%80%E5%A7%8B%E8%B0%83%E8%AF%95

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: Weex Playground crashes frequently during debugging and cannot open js debugging.

As weex devtools is never part of Apache, you should ask question in there [repo](https://github.com/weexteam/weex-toolkit), not here.
