### ISSUE TITLE
安卓手势监听嵌套scoller尽快适配呗，现在处理起来太麻烦了。请尽快适配

### ISSUE THREAD

**Issue by bam-boo** [apache/incubator-weex-site#413]
https://weex.apache.org/zh/docs/events/gesture.html#属性

**Comment by YorkShen** [comment]
感谢你的反馈，Weex目前是隶属于Apache Software Foundation的项目，因此在Gtihub渠道我们鼓励使用英文反馈问题。下面我将使用Google Trasnlate将你的问题翻译成英语，并以英语回答。

> Question Description: The Android gesture monitoring nested scoller adapts as soon as possible, and now it is too cumbersome to handle. Please adapt as soon as possible.

Github issue is only used for bug report, not feature request. Feel free to join the [mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list) and discuss the feature.
