### ISSUE TITLE
error js code "console.log('callback: ', event })"

### ISSUE THREAD

**Issue by xiaoyang678** [apache/incubator-weex-site#414]
```
var navigator = weex.requireModule('navigator')
navigator.push({
  url: 'http://dotwe.org/raw/dist/519962541fcf6acd911986357ad9c2ed.js',
  animated: "true"
}, event => {
  console.log('callback: ', event })
})
```
whats this  console.log('callback: ', event })???

**Comment by YorkShen** [comment]
It's obvious there is a syntax error.

`console.log('callback: ', event })` should change to  `console.log('callback'+event )`. If this is a issue about our document, please give us a PR, thanks.
