### ISSUE TITLE
In Built-in module modal, if too many words in toast or alert, modal can not be displayed properly

### ISSUE THREAD

**Issue by gukui27** [apache/incubator-weex-site#419]
https://weex.apache.org/zh/docs/modules/modal.html#prompt

In Built-in module modal, if too many words in toast or alert, modal can not be displayed properly
https://i.loli.net/2019/06/10/5cfdbae33d82037442.png

**Comment by YorkShen** [comment]
I think this is a bug, please move this issue to [weex-sdk issue](https://github.com/apache/incubator-weex). I will handle it there
