### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by dying318** [apache/incubator-weex-site#423]
https://weex.apache.org/zh/docs/modules/picker.html#pickdate

**Comment by YorkShen** [comment]
It looks good on my Android/iOS phone.

The web doesn't suppor it.

**Comment by dying318** [comment]
I mean this page: http://dotwe.org/vue/5edb9cb54c0af10592abac950b6f780f, when click pick button, a js error occurred.

**Comment by YorkShen** [comment]
Still, looks good on my Android and iOS phone

**Comment by dying318** [comment]
Neither was ok on chrome or my iPhone, I test this page also, http://dotwe.org/raw/htmlVue/5edb9cb54c0af10592abac950b6f780f?1561016279171&p=true, nothing happened when I click pick, even a js error.

**Comment by YorkShen** [comment]
You are using the wrong address.

Scan the QR code in http://dotwe.org/vue/5fdb67685e4cf8eee1f4aa496a9c22c1 with your phone, not click it.

**Comment by dying318** [comment]
It's ok, thanks a lot.
