### ISSUE TITLE
[Missing document] Android NDK 18

### ISSUE THREAD

**Issue by YorkShen** [apache/incubator-weex-site#427]
As Weex upgraded from NDK 16 to 18, the following document need to change:

* https://weex.apache.org/guide/develop/integrate-to-android-app.html#_1-configure-dependency 
* https://github.com/apache/incubator-weex/blob/master/README.md
* https://github.com/apache/incubator-weex/blob/master/HOW-TO-BUILD.md

**Comment by Darin726** [comment]
Pr
https://github.com/apache/incubator-weex-site/pull/430
https://github.com/apache/incubator-weex/pull/2586
