### ISSUE TITLE
The parameter interpretation of the getComponentRect method of the dom module is ambiguous

### ISSUE THREAD

**Issue by dczxw** [apache/incubator-weex-site#445]
https://weex.apache.org/zh/docs/modules/dom.html#getcomponentrect

**getComponentRect**
获取某个元素 View 的外框。

# getComponentRect(ref, callback)
@ref，要滚动到的那个节点。
@callback，异步方法，通过回调返回信息。

The Chinese interpretation of the parameter ref is ambiguous；

The best explained is：要获取外框的那个节点

Suggested changes！

**Comment by YorkShen** [comment]
Please give us a PR, thanks
