### ISSUE TITLE
recycle-list android端不可用

### ISSUE THREAD

**Issue by sihangfeiyu** [apache/incubator-weex-site#458]
recycle-list android端不可用

**Comment by YorkShen** [comment]
Please provide a [demo](http://dotwe.org/vue) and I am really happy if you could give us a PR to fix the problem, we can talk implementation detail in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)
