### ISSUE TITLE
recycle-list下拉刷新问题，为什么不能套用下拉刷新组件，怎么实现下拉刷新

### ISSUE THREAD

**Issue by JiangWen1995** [apache/incubator-weex-site#470]
https://weex.apache.org/zh/docs/components/recycle-list.html#%E7%A4%BA%E4%BE%8B

**Comment by YorkShen** [comment]
1. It doesn't support.
2. If this still bothers you, you could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)
