### ISSUE TITLE
waterfall不作为根元素时在ios手机上无法滑动，因为我们项目的原因，不能作为根元素，这个问题有办法解决吗？

### ISSUE THREAD

**Issue by JiangWen1995** [apache/incubator-weex-site#472]
https://weex.apache.org/zh/docs/components/waterfall.html#%E7%A4%BA%E4%BE%8B

**Comment by YorkShen** [comment]
1. I think this is just not supported.
2. If this still bothers you, you could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)
