### ISSUE TITLE
autopaly  auto-play 参数不生效

### ISSUE THREAD

**Issue by CheneyWong** [apache/incubator-weex-site#478]
https://weex.apache.org/zh/docs/components/video.html

示例中的视频坏了，换了能用的视频，自动播放也不生效。

**Comment by YorkShen** [comment]
1. As it metioned in the document, `You should consider <video> as demo purpose, and re-implement it your favourite video library.`
2. If this still bothers you, you could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)
