### ISSUE TITLE
IOS上的scoller无法使用position来设置高度

### ISSUE THREAD

**Issue by handezhao** [apache/incubator-weex-site#480]

**Comment by YorkShen** [comment]
1. This is just not supported now.
2. If this still bothers you, you could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8).
