### ISSUE TITLE
换成任何第三方的正常URL都无法获取到数据

### ISSUE THREAD

**Issue by liuzhao** [apache/incubator-weex-site#481]
https://weex.apache.org/zh/docs/modules/stream.html#fetch

除了官方的URL之外，其他的URL都返回Network Error!  这是为啥啊？

**Comment by YorkShen** [comment]
1. Without a [demo](http://dotwe.org/vue), there is nothing I can do.
2. If this still bothers you, you could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)
