### ISSUE TITLE
错别子

### ISSUE THREAD

**Issue by kqiu** [apache/incubator-weex-site#489]
https://weex.apache.org/zh/guide/use-vue-in-weex.html#%E6%94%AF%E6%8C%81%E7%9A%84%E5%8A%9F%E8%83%BD

便于->编译

**Comment by dilbert2** [comment]
https://weex.apache.org/zh/guide/front-end-frameworks.html#%E6%A1%86%E6%9E%B6%E7%B1%BB%E5%9E%8B%E6%A0%87%E8%AE%B0
所有可代码之前->所有可执行代码之前

https://weex.apache.org/zh/guide/use-vue-in-weex.html#%E5%B9%B3%E5%8F%B0%E7%9A%84%E5%B7%AE%E5%BC%82
出现性能考虑-> 出于

**Comment by YorkShen** [comment]
Thanks for the help of cnryb.
