### ISSUE TITLE
富文本设置最大行数没用

### ISSUE THREAD

**Issue by zhanglinfeng** [apache/incubator-weex-site#494]
https://weex.apache.org/zh/docs/components/richtext.html#%E4%BA%8B%E4%BB%B6

**Comment by YorkShen** [comment]
1. According to documentation, `lines` is only supported in `<richtext>` itself, not its children node.
2. If this still bothers you, you could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)
