### ISSUE TITLE
week的线性渐变问题

### ISSUE THREAD

**Issue by GoodBaiYu** [apache/incubator-weex-site#495]
https://weex.apache.org/zh/docs/styles/common-styles.html#%E4%B8%8A%E6%89%8B%E6%A0%B7%E5%BC%8F

Weex 目前只支持两种颜色的渐变，渐变方向如下：

to right：从左向右渐变
to left：从右向左渐变
to bottom：从上到下渐变
to top：从下到上渐变
to bottom right：从左上角到右下角
to top left：从右下角到左上角

**非常奇怪的问题：为什么没有to bottom left、 to top right两个方向呢？方向不完备**

**Comment by YorkShen** [comment]
1. This is just not supported.
2. If this still bothers you, you could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)
