### ISSUE TITLE
'实例' 运行在weexplayground查看不到设备的信息

### ISSUE THREAD

**Issue by zhengminmao** [apache/incubator-weex-site#497]
https://weex.apache.org/zh/docs/modules/deviceInfo.html#enablefullscreenheight

**Comment by YorkShen** [comment]
1. Try upgrade to `Weex 0.28`.
2. If this still bothers you, you could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)
