### ISSUE TITLE
希望提供更全面的Abis

### ISSUE THREAD

**Issue by HZHAndroid** [apache/incubator-weex-site#500]
希望提供全面的Abis，由开发者自己的去决定要使用哪种cpu架构，否则对用户的影响很大，受到了很大的限制。

**Comment by YorkShen** [comment]
Weex contains C++ code, so it's not possible to support all ABI. However, Weex 0.28 supports the fowlloings:
* x86
* armeabi-v7a
* arm64-v8a

If you want x86-64 support, you can read [this email](https://lists.apache.org/thread.html/334a6addf8fcacd580ba1c0b00f8770a38de8351ef65917c5f045af4@%3Cdev.weex.apache.org%3E) and contact me in the [mailing list](https://weex.apache.org/guide/contribute/how-to-contribute.html#mailing-list), then you can write a PR.
