### ISSUE TITLE
集成到Android应用，网页上demo链接都404了

### ISSUE THREAD

**Issue by folee** [apache/incubator-weex-site#501]
https://weex.apache.org/zh/guide/develop/integrate-to-android-app.html#_6-%E8%BF%90%E8%A1%8Capp

**Comment by xiaoyang678** [comment]
没有吧，这个？可能是网络问题
![image](https://user-images.githubusercontent.com/44967277/65653981-ca227100-e049-11e9-85c0-23ef52f31068.png)

**Comment by YorkShen** [comment]
It work well, now.
