### ISSUE TITLE
weex-amap 地图插件add时，不被支持了

### ISSUE THREAD

**Issue by operationdll** [apache/incubator-weex-site#504]
weex-amap 地图插件add时，不被支持了

Why is not support weex-amap?

**Comment by YorkShen** [comment]
As it's said in [Amap project](https://github.com/weex-plugins/Amap-for-Apache-Weex)

    Amap for Apache Weex is a third party plugin, and is not developed nor maintained by Apache Weex.

We are not responsible for this.
