### ISSUE TITLE
【webSocket & HELP】How to use webSocket on Android?

### ISSUE THREAD

**Issue by Moon1102** [apache/incubator-weex-site#505]
The document (https://weex.apache.org/zh/docs/modules/websockets.html#websocket-2) mentions that on Android, we should implement an adapter by ourselves, but file link was dead(404 not found).Then I search all github but result of keyword `DefaultWebSocketAdapter` was not found.

And when I try demo(http://dotwe.org/vue/5726b11ba5a4279a2f221650dfcf9e69) on PC,it works well,but copy all code to my project and run it on Android phone,no response. Whatever I use code style like `websocket.onopen = ()=>{  xxx  }` or `websocket.onopen(()=>{ xxx })`

It make me a little confused. Anyone can help me?  I'll appreciate.

**Comment by YorkShen** [comment]
There is a project refactoring, which cause the 404. I have updated the site. https://github.com/apache/incubator-weex-site/pull/534

FYI: You can alwasy ask question in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8), where pepole will answer you in time.
