### ISSUE TITLE
Textarea return-key-type func does not work on android

### ISSUE THREAD

**Issue by dingchaofa** [apache/incubator-weex-site#507]
Example:  http://dotwe.org/vue/bcac7592b6f251a33d21bb647051cabb
1、
如果指定return-key-type=go，则必须指定type=text，然而这样就不能换行了。So sad!

2、
textarea 的属性singleline，在安卓上同样无效。

**Comment by YorkShen** [comment]
1. The supported attributes are listed in [document](https://weex.apache.org/zh/docs/components/textarea.html#%E6%A0%B7%E5%BC%8F), where `return-key-type` and `singleline` are not supported.
2. You could give us a PR if you can, I am very happy to talk with you implemenation detail or review you PR in [mailing list](https://weex.apache.org/zh/guide/contribute/how-to-contribute.html#%E9%82%AE%E4%BB%B6%E5%88%97%E8%A1%A8)
