### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by lutan8673** [apache/incubator-weex-site#510]
https://weex.apache.org/zh/docs/styles/text-styles.html#%E5%B1%9E%E6%80%A7

![image](https://user-images.githubusercontent.com/50561526/67469709-28f5fd00-f67f-11e9-92f3-b5407363bd7d.png)

文本样式 属性 中的 text-align 属性的标题写错了

**Comment by cnryb** [comment]
看起来可以关闭了

**Comment by lutan8673** [comment]
辛苦了
