### ISSUE TITLE
eeui中的内容真够可以的，看来开发这个项目的人员都是色狼哦

### ISSUE THREAD

**Issue by caoguofang** [apache/incubator-weex-site#543]
https://weex.apache.org/zh/tools/eeui.html#%E6%8F%92%E4%BB%B6%E5%B8%82%E5%9C%BA

**Comment by YorkShen** [comment]
What's problem here, I installed their app, everything is fine to me.

**Comment by netzhouxiang** [comment]
你不懂普通话？13都装肿了

**Comment by YorkShen** [comment]
@netzhouxiang According to Weex [Code of Conduct](https://github.com/apache/incubator-weex/blob/master/CODE_OF_CONDUCT.md), **Public or private harassment** is not allowed.
