### ISSUE TITLE
使用了改完包名的weex sdk  0.28版本，weex 初始化总是失败

### ISSUE THREAD

**Issue by dannyzhuang** [apache/incubator-weex-site#545]
weex 初始化的时候调用 `WXSDKEngine.initialize(SuningApplication.getInstance(), config);` ，weex sdk中会调用方法`initFrameworkEnv` 如图：
![QQ图片20191109112104](https://user-images.githubusercontent.com/4216851/68522200-95116b80-02e3-11ea-8632-bff162134ef9.png)

这个方法初始化的时候  initFrameworkEnv方法停留了很长时间，最终失败，走到else里面去
![QQ图片20191109112122](https://user-images.githubusercontent.com/4216851/68522191-8034d800-02e3-11ea-93db-b49ed7ffb0b9.png)

造成

![5555](https://user-images.githubusercontent.com/4216851/68522713-6dbd9d00-02e9-11ea-8137-27e61201be02.png)

我业务代码里面，每次跳转到weex的时候，都会判断weex 是否已经被初始化了：
`WXSDKEngine.isInitialized()`  如果没有初始化，我就不会跳转到weex 页面。

![Uploading 222.png…]()

同时看到初始化的时候有异常log：

 
![666](https://user-images.githubusercontent.com/4216851/68522615-1c60de00-02e8-11ea-8924-b958f2a4cea8.png)

**Comment by YorkShen** [comment]
`com.taobao.windmill` is something verbose, an we will delete it soon.

As for your problem, you may want to have a look at https://github.com/apache/incubator-weex/issues/3003

**Comment by yjouyang** [comment]
Same problem!

**Comment by YorkShen** [comment]
Read the releated Github Issues first,
* https://github.com/apache/incubator-weex/issues/3030
* https://github.com/apache/incubator-weex/issues/3013

Just make sure all the .so files in `weex.aar` also exists in your apk. That's the reason for all the similar issuses.

**Comment by yjouyang** [comment]
@YorkShen Thanks for your reply! Problem solved by copying jsc to my project. By the way, you might want to update this [document](https://weex.apache.org/zh/guide/develop/integrate-to-android-app.html)

**Comment by YorkShen** [comment]
> @YorkShen Thanks for your reply! Problem solved by copying jsc to my project. By the way, you might want to update this [document](https://weex.apache.org/zh/guide/develop/integrate-to-android-app.html)

Actually, you're better than me when talking about editing documentation. You met the problem and showed us the ability to solve it, while I only knew how things worked theoretically.

On bottom of each document page, there is a button to allow you create a Github Pull request to reword the document.
