### ISSUE TITLE
getComponentRect ref desc wrong

### ISSUE THREAD

**Issue by lebronding** [apache/incubator-weex-site#547]
https://weex.apache.org/zh/docs/modules/dom.html#getcomponentrect

#getComponentRect(ref, callback)
@ref，要滚动到的那个节点。
@callback，异步方法，通过回调返回信息。

@ref，要滚动到的那个节点。这个应该不是滚动的节点吧，应该是要获取的节点

**Comment by YorkShen** [comment]
如果发现文档有问题，请给我们提交 PR。
