### ISSUE TITLE
Weex Devtools Debugger的技术选型实录 似乎在阿里内网

### ISSUE THREAD

**Issue by cnryb** [apache/incubator-weex-site#548]
https://weex.apache.org/zh/guide/debug/integrate-devtool-to-android.html#%E7%A7%91%E6%99%AE

Weex Devtools Debugger的技术选型实录 文章似乎在阿里内网，不知道方不方便公布出来呀

**Comment by YorkShen** [comment]
我帮你找到了这篇文章的作者，你可以联系[他](https://github.com/littleseven) 获取帮助。

由于这两篇文章的作者都不是我，因此我没有权利去公开这篇文章。
