### ISSUE TITLE
博客文章中使用的图片大量403异常

### ISSUE THREAD

**Issue by cnryb** [apache/incubator-weex-site#556]
https://weex.incubator.apache.org/zh/blog/ios-weexcore.html#_0x33-layout-%E9%80%BB%E8%BE%91%E4%BF%AE%E6%94%B9

博客栏目中图片大多都是用了CDN，大量图片在加载过程中出现403异常。
是不是CDN的配置有问题了呀。
还是把咱把图片都搬到GitHub上来呀

**Comment by YorkShen** [comment]
1. 由于博客的作者众多，一些作者喜欢将图片部署在 CDN 上，一些作者喜欢将图片上传到 Github 上。
2. 我觉得将博客图片放置到 Github 上是合理的。目前所有已发布的博客均处于 Apache 协议的授权下，因此对博客进行二次编辑不存在法律问题/风险。
3. @cnryb 目前 Weex 网站采用 Vuepress 构建，故你可以将博客中的图片移动至[相应目录](https://github.com/apache/incubator-weex-site/tree/master/docs/.vuepress/public)，并更改博客中的链接。

**Comment by cnryb** [comment]
好的，那我抽空搞一下吧

**Comment by YorkShen** [comment]
Solved
