### ISSUE TITLE
推荐weex 做出类似于css var(--color) 或者scss  $baseColor类似的全局样式变量

### ISSUE THREAD

**Issue by wegi8** [apache/incubator-weex-site#564]
https://weex.apache.org/zh/docs/styles/color-name.html

**Comment by YorkShen** [comment]
1. GitHub issues is used to report bug, not to discuss features.
2. If you want something, prepare a proposal with your API desgin in mailing list. Commmitters here are doing things for free or for their interest, they are not working for you.
