### ISSUE TITLE
getComponentRect方法的参数描述错误

### ISSUE THREAD

**Issue by kexianwang** [apache/incubator-weex-site#568]
getComponentRect(ref, callback)
@ref  这个地方的描述应该是：要获取外框的那个节点

**Comment by cnryb** [comment]
不知道您方不方便帮助我们改进文档呀。
在对应页面的底部，更新时间和`提交建议`之间，有个链接 `编辑此页`。点击编辑此页，可以直接修改你认为不完美的地方。之后发一个pr过来就好了。
