### ISSUE TITLE
demo初始化源码链接不正确，应该是https://github.com/apache/incubator-weex-playground/blob/master/android/playground/src/main/java/org/apache/weex/WXApplication.java

### ISSUE THREAD

**Issue by yangtao0619** [apache/incubator-weex-site#571]
https://weex.apache.org/zh/guide/develop/integrate-to-android-app.html#_7-%E6%89%A9%E5%B1%95android%E8%83%BD%E5%8A%9B

**Comment by cnryb** [comment]
感谢您的反馈，已经修复等待发布了。
其实您可以直接在页面底部点击 `编辑此页` 对发现问题的文档进行修改。
