### ISSUE TITLE
具体的api，方法名有哪些呢？

### ISSUE THREAD

**Issue by theGreatTomato** [apache/incubator-weex-site#573]
https://weex.apache.org/zh/docs/modules/globalEvent.html#addeventlistener

**Comment by cnryb** [comment]
现在只有文档中的那些，你可以看一下具体的代码。
[android](https://github.com/apache/incubator-weex/blob/master/android/sdk/src/main/java/org/apache/weex/WXGlobalEventModule.java)
[iOS](https://github.com/apache/incubator-weex/blob/e82a37236ce8eeffe49f1bbacc20cbeec70bcd43/ios/sdk/WeexSDK/Sources/Module/WXGlobalEventModule.m)
