### ISSUE TITLE
「Weex Devtools Debugger的技术选型实录」文档链接为阿里内网链接，希望公开出来

### ISSUE THREAD

**Issue by anchengjian** [apache/incubator-weex-site#576]
Weex Devtools Debugger的技术选型实录: http://www.atatech.org/articles/59284?spm=a2c7j.-zh-guide-debug-integrate-devtool-to-android.0.0.103e6d4cEWN0pG

这个链接需要登陆阿里内部账号，希望能公开出来

![image](https://user-images.githubusercontent.com/8679331/75662205-abd03980-5ca9-11ea-9e88-e723ab791f80.png)

https://weex.apache.org/zh/guide/debug/integrate-devtool-to-android.html#%E7%A7%91%E6%99%AE

**Comment by cnryb** [comment]
Duplicate of #548
