### ISSUE TITLE
快速上手 一点都不快速

### ISSUE THREAD

**Issue by KeymonWong** [apache/incubator-weex-site#577]
https://weex.apache.org/zh/guide/develop/integrate-to-iOS-app.html#_6-%E5%9C%A8-ipad-%E4%B8%AD%E4%BD%BF%E7%94%A8-weex

_instance.onCreate = ^(UIView *view) {
        [weakSelf.weexView removeFromSuperview];
        weakSelf.weexView = view;
        [weakSelf.view addSubview:view];
 };

weexView是什么？ wxsdk初始化的时候引用头文件不说明，让新手猜吗？文档都写不清楚、详细，细节都做不好，谈什么大前端一统天下，不能怪别人菜 这文档和快速上手有悖

**Comment by cnryb** [comment]
对，都是敌人太强大了……
你可以跑一下 [playground](https://github.com/apache/incubator-weex-playground) 有助于更快速的了解整个运行过程。
你有异议的完整代码在这里
https://github.com/apache/incubator-weex-playground/blob/master/ios/WeexDemo/WXDemoViewController.m#L174-L178

文档确实不够好，非常欢迎你能帮助改进。

**Comment by KeymonWong** [comment]
> 对，都是敌人太强大了……
> 你可以跑一下 [playground](https://github.com/apache/incubator-weex-playground) 有助于更快速的了解整个运行过程。
> 你有异议的完整代码在这里
> https://github.com/apache/incubator-weex-playground/blob/master/ios/WeexDemo/WXDemoViewController.m#L174-L178
> 
> 文档确实不够好，非常欢迎你能帮助改进。

感谢！所以我自己挑着源码搂了一眼。对了 sdk 里面有用 UIWebview 的，苹果不是不让使用了么？不打算优化一下吗？被拒可能性大

**Comment by cnryb** [comment]
源码里已经修了这个问题了。https://github.com/apache/incubator-weex/pull/3053

**Comment by YorkShen** [comment]
@KeymonWong 关于苹果审核政策，可以参考[这个](https://lists.apache.org/thread.html/fdf5f7d44e739d0814b41e12721b161b0946fc544f0a1707fec7f5c3%40%3Cdev.weex.apache.org%3E).

**This update has nothing to do with Weex Apps, but Apps that people try to load from a remote server. Try not to load code from a server if your App(s) falls into the case mentioned above**
