### ISSUE TITLE
iOS的UIWebView迁移至WKWebView

### ISSUE THREAD

**Issue by zhouming0100** [apache/incubator-weex-site#578]
2020年4月份，新App不在接受UIWebView，12月份将不能使用UIWebView。希望新版本的SDK，尽快使用WKWebView替换旧的UIWebView。

**Comment by cnryb** [comment]
Related issue: https://github.com/apache/incubator-weex/issues/3162 ,  https://github.com/apache/incubator-weex/issues/2866

Fixed by https://github.com/apache/incubator-weex/pull/3053

**Comment by WJHCode** [comment]
pod集成的WeexSDK，最新版0.28.0还是包含UIWebView的，请问何时更新pod版本？
