### ISSUE TITLE
weex 组建中的 自带 <video>  如何用自己喜欢的 视频播放库 比如说 腾讯云家的  进行二次封装呢；  没有文档

### ISSUE THREAD

**Issue by RobotJohns** [apache/incubator-weex-site#598]
https://weex.io/

**Comment by cnryb** [comment]
可以扩展component以实现你的需求。  
https://weex.apache.org/zh/guide/extend/extend-android.html#component-%E6%89%A9%E5%B1%95
更详细的你可以查看 SDK 源码中，组件的实现以及注册方式。

**Comment by RobotJohns** [comment]
多谢 已经看到一些这方面的资料，
😂

任跃兵 <notifications@github.com> 于2020年10月29日周四 上午9:54写道：
